# Szymon Szewczyk
# Naural Network Classification

In [57]:
import numpy as np
import keras
from keras.datasets import mnist
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

### Load and data conversion

In [58]:
training_set, test_set = mnist.load_data()

X_train, y_train = training_set
X_test, y_test = test_set

X_train.shape

(60000, 28, 28)

In [59]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
X_train.shape

(60000, 28, 28, 1)

In [60]:
X_train = X_train.astype(np.float64)/255.0
X_test = X_test.astype(np.float64)/255.0

### Conditions

In [61]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

### Model

In [62]:
model = keras.Sequential([

    keras.Input(shape=input_shape),
    keras.layers.Flatten(),
    layers.Dense(num_classes, activation='softmax')
])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_6 (Flatten)         (None, 784)               0         
                                                                 
 dense_8 (Dense)             (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [63]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Model training

In [64]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 2ms/step - loss: 0.7523 - accuracy: 0.8140 - val_loss: 0.4095 - val_accuracy: 0.8953
Epoch 2/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3897 - accuracy: 0.8970 - val_loss: 0.3349 - val_accuracy: 0.9095
Epoch 3/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3384 - accuracy: 0.9074 - val_loss: 0.3075 - val_accuracy: 0.9156
Epoch 4/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3145 - accuracy: 0.9131 - val_loss: 0.2944 - val_accuracy: 0.9175
Epoch 5/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3001 - accuracy: 0.9171 - val_loss: 0.2840 - val_accuracy: 0.9222
Epoch 6/30
375/375 [==============================] - 1s 2ms/step - loss: 0.2907 - accuracy: 0.9189 - val_loss: 0.2786 - val_accuracy: 0.9233
Epoch 7/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2834 - accuracy: 0.9212 - val_loss: 0.2741 - val_accuracy: 0.9250
Epoch 

In [65]:
model.save("linear.h5")

### Model evaluation

In [66]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 1s 1ms/step


In [67]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.92      0.91      0.91      1032
           3       0.90      0.91      0.91      1010
           4       0.93      0.93      0.93       982
           5       0.92      0.86      0.89       892
           6       0.95      0.95      0.95       958
           7       0.93      0.92      0.93      1028
           8       0.88      0.90      0.89       974
           9       0.92      0.91      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 965    0    1    2    0    5    4    2    1    0]
 [   0 1113    3    3    0    1    3    2   10    0]
 [   4    9  938   13    6    3   11    8   37    3]
 [   3    0   23  920    0   23    2   12   21    6]
 [   1    1    8    1  914   

## MLP model

In [69]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_8 (Flatten)         (None, 784)               0         
                                                                 
 dense_12 (Dense)            (None, 64)                50240     
                                                                 
 dense_13 (Dense)            (None, 128)               8320      
                                                                 
 dense_14 (Dense)            (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [70]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 2s 4ms/step - loss: 0.4034 - accuracy: 0.8874 - val_loss: 0.2252 - val_accuracy: 0.9360
Epoch 2/30
375/375 [==============================] - 1s 3ms/step - loss: 0.1954 - accuracy: 0.9428 - val_loss: 0.1697 - val_accuracy: 0.9502
Epoch 3/30
375/375 [==============================] - 1s 3ms/step - loss: 0.1424 - accuracy: 0.9586 - val_loss: 0.1422 - val_accuracy: 0.9578
Epoch 4/30
375/375 [==============================] - 1s 4ms/step - loss: 0.1105 - accuracy: 0.9676 - val_loss: 0.1178 - val_accuracy: 0.9660
Epoch 5/30
375/375 [==============================] - 1s 4ms/step - loss: 0.0891 - accuracy: 0.9735 - val_loss: 0.1214 - val_accuracy: 0.9639
Epoch 6/30
375/375 [==============================] - 1s 4ms/step - loss: 0.0731 - accuracy: 0.9778 - val_loss: 0.1092 - val_accuracy: 0.9667
Epoch 7/30
375/375 [==============================] - 2s 4ms/step - loss: 0.0615 - accuracy: 0.9815 - val_loss: 0.1022 - val_accuracy: 0.9707
Epoch 

In [72]:
model.save("mlp.h5")

In [73]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 1ms/step
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.97      0.98       892
           6       0.98      0.98      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.98      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 968    0    2    0    0    2    5    1    2    0]
 [   0 1124    2    2    0    0    2    1    4    0]
 [   5    1 1005    4    2    1    3    3    8    0]
 [   1    2    5  986    2 

## Convolutional network

In [74]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_9 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [75]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 25s 66ms/step - loss: 0.3852 - accuracy: 0.8835 - val_loss: 0.0970 - val_accuracy: 0.9737
Epoch 2/30
375/375 [==============================] - 25s 67ms/step - loss: 0.1116 - accuracy: 0.9658 - val_loss: 0.0676 - val_accuracy: 0.9804
Epoch 3/30
375/375 [==============================] - 24s 65ms/step - loss: 0.0841 - accuracy: 0.9734 - val_loss: 0.0537 - val_accuracy: 0.9846
Epoch 4/30
375/375 [==============================] - 24s 63ms/step - loss: 0.0715 - accuracy: 0.9777 - val_loss: 0.0494 - val_accuracy: 0.9858
Epoch 5/30
375/375 [==============================] - 25s 67ms/step - loss: 0.0610 - accuracy: 0.9809 - val_loss: 0.0439 - val_accuracy: 0.9874
Epoch 6/30
375/375 [==============================] - 27s 72ms/step - loss: 0.0555 - accuracy: 0.9827 - val_loss: 0.0448 - val_accuracy: 0.9872
Epoch 7/30
375/375 [==============================] - 24s 65ms/step - loss: 0.0513 - accuracy: 0.9841 - val_loss: 0.0415 - val_accuracy:

In [76]:
model.save("conv.h5")

In [77]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 4ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       980
           1       1.00      1.00      1.00      1135
           2       1.00      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      1.00      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.99      1.00      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 977    0    0    0    1    0    0    1    1    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [   1    0 1022    0    2    0    0    7    0    0]
 [   0    0    1 1004    0 